FORMAT: 1A
HOST: https://prms.fjaus.com

# FJA-US Product Machine Runtime Service Reference API
The Product Machine Runtime Service (PMRS) is the runtime component of the Product Machine.
This component exposes varies services that can be called by consuming applications to perform calculation
and validation services. It also can be used to retrieve information about products and covers.

Finally, it exposes meta information about the input data required to call calculation and validation routines.
This document describes the main features of this component and provides details about
the service calls available.

The interface is designed to have predictable, resource-oriented URLs whenever possible and to use HTTP
response codes to indicate API errors.
The API relies on the built-in HTTP features e.g. HTTP authentication, HTTP verbs, HTTP headers, etc.

# Version
1.1

# Authentication
API users are required to obtain an authentication token by passing user ID and password to FJA-US User Mangement Module (UMM) via its REST API. 
Prior to receiving  a token the user must be created and configured in UMM. The token must be subsequently 
used on all API requests. The tokens have expiration time which is a configurable parameter in UMM application.
THe system does not allow multiple tokens per single user ID.

# Authorization
Each request to API translates the supplied token into the user's action rights and domains,
The user's access to resources is based on the combination of the above. For example,

*  An action right **.product.validate** allows its holder to validate context
*  A domain ***business.ACME*** provides access to product information  ***ACME-Life***, ***ACME-Life-Optional***, and ***ACME-Disability***


# Base URI

All requests will extend URL **https://prms.fjaus.com/services/version/**

# Content

## Request

The request content has to be submitted in XML compatible with one the following XML schemes:

* FJA-US Health **https://schemas.fjaus.com/current/HealthRef.xsd**
* FJA-US Group Life  **https://schemas.fjaus.com/current/GroupInsurance.xsd**
* FJA-US Property and Casualty  **https://schemas.fjaus.com/current/PandC.xsd**

The client must provide HTTP header **content-type: application/xml**


## Response

The response type is XML which is compatible with the following schema:

* FJA-US Product Machine Services ***https://schemas.fjaus.com/current/ProductMachine.xsd**

The client must provide HTTP header **accept: application/xml**


## Samples 

Additionally see the various requests and responses samples in XML format at

* Health samples **https://samples.fjaus.com/health/current/samples**
* Group Life samples **https://samples.fjaus.com/groupinsurance/current/samples**
* Property and Casualty samples **https://samples.fjaus.com/pandc/current/samples**


# Common Response Codes

* 200 **OK** Successfully completed a retrieval request
* 400 **Bad Content** Invalid content or business logic failure
* 401 **Not Authenticated** A request cannot be authenticated by the server
* 403 **Forbidden** Authorization failure
* 404 **Not Found** A resource is not found
* 405 **Bad Method** An unsupported HTTP method
* 419 **Authentication timeout** expired authentication token
* 500 **Server Error** A run time error on server

# HTTP Verbs Usage

Given the typical payload size for these services HTTP POST is used instead of HTTP GET for some requests.

# Group Products

## Root Product Components [/products/?{tokenKey}]

Retrieves information about the product components at the root of the hierarchy.
Only the version information is taken into consideration.


### List all avaliable root products components [GET]
+ Parameters
    + tokenKey (required, string) ... authentication token

+ Request
    + Body

            Refer to FJA-US Health, Group Life, and Property and Casualty XML schemas and the applicable request samples

+ Response 200 (application/xml)
    + Body

            Refer to FJA-US Product Machine Services XML schema and the request samples


## Product Components [/products/{productType}/?{tokenKey},{contextFree},{includeUnvailable},{deep}]
### Retrieve unfiltered product components [POST]
+ Parameters
    + tokenKey (required, string) ... authentication token
    + productType (required, string) ... type is an unique identifier within product definition
    + contextFree (optional, boolean) ...    when true no formulas are executed during availability processing, otherwise full processing is done
    + includeUnvailable (optional, boolean) ... if set to true components and group constraint rules which are unavailable will be returned, and children will be processed
    + deep (optional, boolean) ... when true process all ancestors of the context component, otherwise only the immediate children are processed

+ Request (application/xml)
    + Body

            Refer to FJA-US Health, Group Life, and Property and Casualty XML schemas and the applicable request samples

+ Response 200
    + Body

            Refer to FJA-US Product Machine Services XML schema and the request samples


## Filtered Product Components [/products/{productType}/filtered/{?tokenKey,contextFree,includeUnvailable,deep}]
### Retrieve filtered product components [POST]
+ Parameters
    + tokenKey (required, string) ... authentication token
    + productType (required, string) ... type is an unique identifier within product definition
    + contextFree (optional, boolean) ... when true no formulas are executed during availability processing, otherwise full processing is done
    + includeUnvailable (optional, boolean) ... if set to true components and group constraint rules which are unavailable will be returned, and children will be processed
    + deep (optional, boolean) ... when true process all ancestors of the context component, otherwise only the immediate children are processed

+ Request (application/xml)
    + Body

            Refer to FJA-US Health, Group Life, and Property and Casualty XML schemas and the applicable request samples

+ Response 200
    + Body

            Refer to FJA-US Product Machine Services XML schema and the request samples


# Group Attributes

## Attributes Without Context [/attributes/{?tokenKey}]
### Populate attributes included on the list  [POST]
+ Parameters
    + tokenKey (required, string) ... authentication token

+ Request (application/xml)
    + Body

            Refer to FJA-US Health, Group Life, and Property and Casualty XML schemas and the applicable request samples
        
+ Response 200
    + Body

            Refer to FJA-US Product Machine Services XML schema and the request samples

## Attributes With Context [/attributes/context/{?tokenKey,includeDomains}]
### Populate attributes based on the context [POST]

The service will build the resulting map of attributes based on the payload in the request body.

+ Parameters
    + tokenKey (required, string) ... authentication token
    + includeDomains (optional, boolean) ... when true the attributes will include list of domain values 

+ Request (application/xml)
    + Body

            Refer to FJA-US Health, Group Life, and Property and Casualty XML schemas and the applicable request samples

+ Response 200
    + Body

            Refer to FJA-US Product Machine Services XML schema and the request samples

# Group Validations

## Validation Results [/validations/{?tokenKey,event,deep}]
### Obtain validation results [POST]

The Validation Service executes all product validation rules and returns a data structure
to the consuming application to communicate rule failures and additional information 
that identifies what logical entities on a policy or quote caused those failures. 

+ Parameters
    + tokenKey (required, string) ... authentication token
    + event (optional, string) ... may be used to exclude validations not applicable to this event
    + deep (optional, boolean) ... when true the context and all its children will be included in the scope
    
+ Request (application/xml)
    + Body

            Refer to FJA-US Health, Group Life, and Property and Casualty XML schemas and the applicable request samples
        
+ Response 200
    + Body

            Refer to FJA-US Product Machine Services XML schema and the request samples
            

# Group Calculations

## Pricing Calculations [/calculations/{?tokenKey}]
### Provide pricing information for the context [POST]

Performs calculations based on the context provided.Typically this returns premiums, taxes, and other fees.
The root object of the calculation is typically an adaptation of a Policy. 
What is returned in the list are typically PremiumComponent objects, 
which each contain a list of PremiumDetail objects.
However, this depends on the implementation of the Calculation Service being used by a given project.

+ Parameters
    + tokenKey (required, string) ... authentication token

+ Request (application/xml)
    + Body

            Refer to FJA-US Health, Group Life, and Property and Casualty XML schemas and the applicable request samples
        
+ Response 200
    + Body

            Refer to FJA-US Product Machine Services XML schema and the request samples